Migrate Centos code to match interfaces modified in eafdb530.
NOTE: The interface was changed after centos_net_manager.go was removed in d6be228a, preventing that code from getting migrated as part of eafdb530. This commit makes the subsequently un-removed centos code compatible with the new interface signature introduced in eafdb530.

---

Current test output (with this commit):

```
bosh-agent % bin/ginkgo platform/net
[1648769063] Net Suite - 141/141 specs ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 20.275451792s PASS
[1648769063] ARP Suite - 3/3 specs ••• SUCCESS! 3.469ms PASS
[1648769063] IP Suite - 19/19 specs ••••••••••••••••••• SUCCESS! 1.718667ms PASS

Ginkgo ran 3 suites in 22.540427083s
Test Suite Passed
```

---

Previous error (before this commit):
```
bosh-agent % bin/ginkgo platform/net
Failed to compile net:

# github.com/cloudfoundry/bosh-agent/platform/net [github.com/cloudfoundry/bosh-agent/platform/net.test]
platform/net/centos_net_manager.go:46:25: cannot use centosNetManager{...} (type centosNetManager) as type Manager in return argument:
        centosNetManager does not implement Manager (wrong type for SetupNetworking method)
                have SetupNetworking(settings.Networks, chan error) error
                want SetupNetworking(settings.Networks, string, chan error) error
[1648766562] ARP Suite - 3/3 specs ••• SUCCESS! 832.041µs PASS
[1648766562] IP Suite - 19/19 specs ••••••••••••••••••• SUCCESS! 1.303166ms PASS

There were failures detected in the following suites:
        net ./platform/net
```

---

Original error (the original commit which was cherrypicked):
```
../platform/net/centos_net_manager.go:47:25: cannot use centosNetManager{...} (type centosNetManager) as type Manager in return argument:
        centosNetManager does not implement Manager (wrong type for SetupNetworking method)
                have SetupNetworking(settings.Networks, chan error) error
                want SetupNetworking(settings.Networks, string, chan error) error
```

# Conflicts:
#	platform/net/centos_net_manager.go